CLASS /dmo/bp_bookingsupplement_u16 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /dmo/i_travel_u16 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /dmo/bp_bookingsupplement_u16 IMPLEMENTATION.
ENDCLASS.
